# SPDX-License-Identifier: GPL-2.0
subdir-y += avnet
subdir-y += iwave
subdir-y += tmoip
subdir-y += bss
subdir-y += bssa
subdir-y += enclustra
subdir-y += xilinx
subdir-y += mlsc
subdir-y += utils-3eg

